name:
  hierachical-hotnet
dependencies:
  - python=2.7
  - numpy=1.13.3
  - scipy=0.19
  - networkX=2.0
  - h5py=2.7.0
  - matplotlib-base=2.2.3
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
